spring:
   profiles:
     active:
     - dev
---
sever:
   port: 8201
spring:
   profiles: dev
   application:
     name: microservicecloud-confi-client
eureka:
   client:
     service-url:
        defaultZone: http://eureka-dev.com:7001/eurka/
---
sever:
   port: 8202
spring:
   profiles: test
   application:
     name: microservicecloud-confi-client
eureka:
   client:
     service-url:
        defaultZone: http://eureka-test.com:7001/eurka/